# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160504_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='destino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='localidad.Colonia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pool',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origen', to='localidad.Colonia'),
        ),
    ]
