# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160519_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='contacto_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='contacto_telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='hora',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
